[package]
name = "memora-api"
version = "0.1.0"
edition = "2024"
default-run = "memora-api"

[dependencies]
axum = { version = "0.8.8", features = ["ws"] }
rand = "0.9"
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }
tokio = { version = "1.49.0", features = ["full"] }
typeshare = "1.0.5"
dotenvy = "0.15.7"
jsonwebtoken = "9.3.0"
uuid = { version = "1.10.0", features = ["serde", "v4"] }
chrono = { version = "0.4.38", features = ["serde"] }
serde_json = "1.0.138"
async-stream = "0.3.6"
futures = "0.3.32"
governor = "0.10.4"
bytes = "1.11.1"
dashmap = "6.1.0"
tower-http = { version = "0.6.8", features = ["cors"] }
bcrypt = "0.18.0"
fsrs = "5.2.0"
reqwest = { version = "0.13.2", default-features = false, features = ["json", "stream", "rustls"] }
base64 = "0.22"

