// Уроки 1–3 курса фонетики. Слова, фразы, лесенки и скороговорки взяты
// из конспектов уроков без изменений — тренируем ровно тот материал,
// который разбирался на занятиях.

import type { PhoneticsLesson } from './corpusTypes';

export const LESSON_1: PhoneticsLesson = {
  n: 1,
  title: 'Согласные и работа речевого аппарата',
  subtitle: 'Твёрдые /k/ и /g/, светлое /l/, увулярное /ʁ/, отсутствие придыхания, [ɲ], «окрашенность» на конечное -e',
  articulation: [
    {
      id: 'art-jaw',
      title: 'Опускание нижней челюсти',
      steps: [
        'Сядьте прямо, расслабьте плечи и лицо.',
        'Медленно опускайте нижнюю челюсть вниз, будто начинаете зевать, — не резко.',
        'Задержитесь на 2 секунды в нижней точке и так же медленно вернитесь.',
        'Повторите 10 раз, следя, чтобы не напрягалась шея.',
      ],
      why: 'Французские гласные требуют большего раскрытия рта, чем русские. Зажатая челюсть — причина того, что [a] и [ɛ] звучат «по-русски», глухо и одинаково.',
      seconds: 45,
    },
    {
      id: 'art-tongue',
      title: 'Гимнастика для языка',
      steps: [
        'Высуньте язык и тянитесь кончиком к носу — 5 раз.',
        'Тянитесь к подбородку — 5 раз.',
        'Упирайтесь языком поочерёдно в левую и правую щёку — по 5 раз.',
        'Проведите языком по внутренней стороне губ полный круг в обе стороны.',
      ],
      why: 'Французские согласные произносятся кончиком языка у зубов, а не у альвеол, как в русском. Языку нужна подвижность и точность, иначе /t/, /d/, /l/, /n/ будут звучать «по-славянски».',
      seconds: 60,
    },
    {
      id: 'art-gargle',
      title: 'Полоскание горла (для увулярного R)',
      steps: [
        'Наберите немного воды и запрокиньте голову.',
        'Полощите горло, прислушиваясь к вибрации маленького язычка (увулы).',
        'Затем без воды воспроизведите ту же вибрацию на выдохе.',
        'Добавьте голос — получится французское [ʁ].',
      ],
      why: 'Именно эта вибрация в глубине рта и есть французское R. Русское раскатистое [р] образуется кончиком языка — совершенно другой механизм.',
      seconds: 60,
    },
  ],
  drills: [
    {
      id: 'k-g',
      lesson: 1,
      ipa: '[k] · [g]',
      title: 'Твёрдые /k/ и /g/ — без смягчения перед a и в конце слова',
      problem: 'Русскоязычные автоматически смягчают k и g рядом с передними гласными и «проглатывают» их в конце слова. Получается «кярт» вместо carte и «мюзик» с призвуком вместо musique.',
      howTo: 'Держите заднюю часть языка твёрдо у мягкого нёба, не подтягивая её вперёд. Согласная в конце слова произносится чётко и до конца — она не оглушается и не исчезает.',
      spellings: ['c + a, o, u → [k]', 'qu → [k]', 'k → [k]', 'g + a, o, u → [g]', 'gu → [g]'],
      words: [
        'carte', 'quatre', 'car', 'karaoké', 'carton', 'canicule', 'capuche', 'cage', 'caprice', 'carafe', 'canari', 'vacances',
        'garage', 'gastronomie', 'gamète', 'gare', 'regards', 'Gaston', 'garçon', 'saga', 'gamme', 'Agathe',
        'musique', 'électrique', 'choc', 'pratique', 'balistique', 'masque', 'ligue', 'figue', 'longue',
      ],
      ladders: [
        {
          steps: [
            "Ce garçon s'appelle Gaston.",
            "Le garçon qui s'appelle Gaston aime la musique classique.",
            "Le garçon qui s'appelle Gaston aime la musique classique et chante en karaoké.",
          ],
          translation: 'Этого мальчика зовут Гастон. → …любит классическую музыку. → …и поёт караоке.',
        },
        {
          steps: [
            'Le canari chante dans sa cage.',
            'Je regarde le canari qui chante dans sa cage.',
            'Pendant la canicule je suis en vacances et je regarde le canari qui chante dans sa cage.',
          ],
          translation: 'Канарейка поёт в клетке. → Я смотрю на канарейку… → В жару я в отпуске и смотрю на канарейку…',
        },
        {
          steps: [
            'Quel vacarme à la gare !',
            'Agathe et Lucas sont à la gare. Quel vacarme !',
            'Agathe et Lucas partent en vacances et ils vont à la gare. Quel vacarme !',
          ],
          translation: 'Какой шум на вокзале! → Агата и Лука на вокзале… → Агата и Лука уезжают в отпуск…',
        },
      ],
    },
    {
      id: 'l-clair',
      lesson: 1,
      ipa: '[l]',
      title: 'Светлое /l/ — всегда одинаковое',
      problem: 'В русском есть два «л»: твёрдое (лампа) и мягкое (лямка). Во французском — только одно, среднее, и оно НЕ меняется ни перед гласной, ни в конце слова. Русское твёрдое «л» в la lune звучит грубо и сразу выдаёт акцент.',
      howTo: 'Кончик языка упирается в основание верхних передних зубов, спинка языка приподнята и не прогибается. Звук светлый, «прозрачный» — одинаковый в la и в elle.',
      words: [
        'la France', 'la lune', 'la lampe', 'la classe', 'la plage', 'la place',
        'la loge', 'locomotive', 'logique', 'logistique', 'plonger', 'le loup', 'la louve', 'la loupe', 'la plouc',
        'universelle', 'transversale', 'Pascal', 'molle', 'folle', 'la balle', 'elle', 'il',
      ],
      ladders: [
        {
          steps: [
            "C'est mon cheval. Il s'appelle Avalac.",
            "Le cheval d'Avalac se lave dans l'eau du lac.",
            "Le cheval d'Avalac se plonge dans l'eau du lac.",
            "Le cheval et le loup se plongent dans l'eau limpide du lac.",
          ],
          translation: 'Это мой конь, его зовут Авалак. → …моется в воде озера. → …ныряет в воду озера. → Конь и волк ныряют в прозрачную воду озера.',
        },
      ],
    },
    {
      id: 'r-uvulaire',
      lesson: 1,
      ipa: '[ʁ]',
      title: 'Французское R — увулярное, «в горле»',
      problem: 'Раскатистое русское [р] кончиком языка во французском звучит чужеродно. Это самый заметный маркер акцента.',
      howTo: 'Звук рождается в глубине рта: вибрирует маленький язычок, кончик языка при этом лежит внизу и не работает. Если увулярное [ʁ] пока не выходит — произносите украинское «г» (фрикативное), оно гораздо ближе к французскому R, чем русское [р].',
      words: [
        'rare', 'Paris', 'crier', 'rural', 'rond', 'la rue', 'la parure', 'rassembler',
        'préparer', 'Robert', 'René', 'privilège', 'murmurer',
      ],
      phrases: [
        'Le mur est noir, quel désespoir !',
        'Dans cette rue noire, on trouve des maisons noires.',
        'Le mur murant Paris rend Paris murmurant.',
        'Un ver vert est dans un verre.',
        'Un ver vert va vers un ver vert qui est dans un verre vert.',
      ],
      twister: 'Le mur murant Paris rend Paris murmurant.',
    },
    {
      id: 'no-aspiration',
      lesson: 1,
      ipa: '[t] · [p] · [k] · [d]',
      title: 'Нет придыхания и нет палатализации',
      problem: 'Две привычки сразу: английское придыхание после p, t, k («тх», «пх») и русское смягчение согласной перед e, i («тьерапия»). Французский не делает ни того, ни другого.',
      howTo: 'Согласная произносится сухо и коротко, без выдоха-«х» после неё. И она не смягчается даже перед é, i, e — язык не подтягивается к нёбу. th читается просто как [t]: thérapie = [teʁapi].',
      words: [
        'littérature', 'thérapie', 'téléréalité', 'panthéon', 'tempête',
        'pédant', 'Théophile', 'Théodore', 'témoignage',
      ],
    },
    {
      id: 'gn',
      lesson: 1,
      ipa: '[ɲ]',
      title: 'GN = [ɲ] — единый мягкий звук',
      problem: 'Читают по буквам «гн», получается два звука вместо одного.',
      howTo: 'Спинка языка прижимается к твёрдому нёбу — выходит единый звук, похожий на «нь» в слове «конья́к», произнесённый слитно.',
      words: ['magnifique', 'ligne', 'épargne', 'magnanime', 'mignon', 'agneau'],
      exceptions: [
        'В словах учёного происхождения gn читается раздельно, как [ɡn], — они вынесены в отдельный блок ниже.',
      ],
    },
    {
      id: 'gn-separate',
      lesson: 1,
      ipa: '[ɡn]',
      title: 'Исключения: gn читается раздельно',
      problem: 'Выучив правило gn = [ɲ], его применяют ко всем словам подряд — и «диагностик» превращается в «дианьостик».',
      howTo: 'В словах учёного происхождения (из греческого и латыни) g и n принадлежат разным морфемам и произносятся ПО ОТДЕЛЬНОСТИ: cognition = [kɔɡnisjɔ̃], а не [kɔɲisjɔ̃]. Сначала звучит [ɡ], затем [n] — так же, как в русском «когнитивный».',
      spellings: ['gn = [ɡn] в учёных словах: cogni-, diagno-, stagn-, gnom-'],
      words: ['cognitif', 'cognition', 'stagner', 'diagnostic', 'gnome'],
      pairs: [
        { a: 'mignon', b: 'cognition', hint: '[miɲɔ̃] единый [ɲ] ↔ [kɔɡnisjɔ̃] раздельные [ɡ]+[n]' },
        { a: 'ligne', b: 'stagner', hint: '[liɲ] ↔ [staɡne]' },
      ],
    },
    {
      id: 'final-e',
      lesson: 1,
      ipa: '[ə̥]',
      title: '«Окрашенность» на конечное -e',
      problem: 'Конечное -e не читается — и русскоязычный обрывает слово, проглатывая согласную перед ним. Из-за этого table звучит как «табл» с исчезающим l, а la cage теряет [ʒ].',
      howTo: 'Конечное -e не произносится как отдельный звук, но заставляет предыдущую согласную прозвучать полностью — с лёгким призвуком-«окрашенностью» после неё. Согласная не обрывается: table = [tabl(ə)], где l слышен до конца.',
      words: [
        'je parle bien', 'quatre pattes', 'quatre ans', 'masque',
        'le sable', 'outre', 'il montre', 'le ventre', "l'ours", 'juste', 'la table', 'le monde',
        'la cage', 'la rage', 'le chômage', 'le garage', 'ma petite sœur', 'mon frère', 'la classe commence',
      ],
    },
    {
      id: 'l1-virelangues',
      lesson: 1,
      ipa: 'virelangues',
      title: 'Скороговорки урока',
      problem: 'Скороговорку пытаются сразу читать быстро — и закрепляют ошибку вместе со скоростью.',
      howTo: 'Сначала по словам, затем медленно целиком, и только потом в темпе. Скороговорка — не проверка на скорость, а тренажёр точности: как только звук поплыл, сбавляйте темп.',
      words: [],
      phrases: [
        'Les nez des poupées de Pépé sont cassés.',
        "Ursule étudie une multitude d'inutilités.",
        'Quatre plats plats dans quatre plats creux et quatre plats creux dans quatre plats plats.',
        'Rat vit rôt, rat mit patte à rôt, rôt brûla patte à rat, rat quitta rôt.',
      ],
    },
  ],
};

export const LESSON_2: PhoneticsLesson = {
  n: 2,
  title: 'Гласные переднего ряда: /i – e – ɛ – a/, /y/, /u/',
  subtitle: 'Закрытое [e] против открытого [ɛ], чтение -er в конце, огублённое [y] против [u], сочетание [ɥi]',
  articulation: [
    {
      id: 'art-lips',
      title: 'Растяжка губ: улыбка ↔ трубочка',
      steps: [
        'Максимально растяните губы в улыбку (позиция [i]) — задержите на 2 секунды.',
        'Резко соберите губы в тугую трубочку (позиция [u]) — задержите на 2 секунды.',
        'Чередуйте 15 раз, наращивая темп.',
        'Затем: губы трубочкой, а язык — как для [i]. Это и есть [y].',
      ],
      why: 'Во французском положение губ и положение языка независимы. Звук [y] (tu, rue) — это язык от [i] плюс губы от [u]. Без натренированных губ он превращается либо в «и», либо в «у».',
      seconds: 60,
    },
  ],
  drills: [
    {
      id: 'e-ferme-ouvert',
      lesson: 2,
      ipa: '[e] · [ɛ]',
      title: 'Закрытое [e] и открытое [ɛ] — разные звуки, разные слова',
      problem: 'Русское «э» — одно, а французских два. Смешение делает речь неразборчивой: слушатель не отличает é от è.',
      howTo: '[e] — рот почти закрыт, губы слегка растянуты, звук напряжённый и короткий. [ɛ] — рот заметно шире, челюсть опущена, звук открытый. Проверьте ладонью под подбородком: на [ɛ] челюсть уходит вниз.',
      spellings: [
        '[e]: é (été, pré, dé); -er и -ied в конце (pied, parler); служебные слова на -s (des, mes, les, tes, ses, ces); окончания futur simple и passé simple (je finirai, j’allai)',
        '[ɛ]: è, ê, ë (très, tête, Noël, près, progrès); e в закрытом слоге (presse, messe, perle); e перед sc (descendre); ai, ei (faire, la neige, beige, la Seine); окончания conditionnel и imparfait (je finirais, j’allais)',
      ],
      words: [
        'la télé', 'la téléréalité', 'ma mémé', 'il écoute', 'elle téléphone', 'répéter', 'préférer', 'pénétrer',
        'la plage', 'la plaine', 'la reine', 'la mère', 'la place', 'il est clair', 'elle est claire',
        'cette belle chapelle', 'des chapelles', 'il descend', 'elle descend', 'elle répète', 'elle préfère', 'elle aime',
      ],
      pairs: [
        { a: 'je finirai', b: 'je finirais', hint: 'futur [e] ↔ conditionnel [ɛ] — разница только в звуке' },
        { a: 'les', b: 'lait', hint: 'служебное слово [e] ↔ ai = [ɛ]' },
        { a: 'été', b: 'êtes', hint: 'é = [e] ↔ ê = [ɛ]' },
      ],
      phrases: [
        'Mémé parle à pépé.',
        'Quelle belle journée !',
      ],
      ladders: [
        {
          steps: [
            'Je vais à la gare pour partir à Cannes.',
            'Je vais à la gare pour partir à Cannes et y passer une belle journée !',
            'Je vais à la gare de Nice pour partir à Cannes et y passer une très belle journée.',
          ],
          translation: 'Я иду на вокзал, чтобы уехать в Канны. → …и провести там прекрасный день! → Я иду на вокзал Ниццы…',
        },
      ],
      exceptions: [
        'ai в ряде слов звучит как [e]: gai, j’ai, je vais, quai, je fais, je sais (мнения расходятся).',
        'Особые слова: ressusciter, ressayer, ressuyer, revolver.',
      ],
    },
    {
      id: 'i-drill',
      lesson: 2,
      ipa: '[i]',
      title: 'Чистое [i] — без призвука',
      problem: 'Русское «и» после согласной смягчает её и само уходит назад. Французское [i] остаётся острым и передним.',
      howTo: 'Губы растянуты в улыбку, кончик языка у нижних зубов, спинка высоко и вперёд. Согласная перед [i] НЕ смягчается.',
      words: [
        'lire des livres', 'la fille', 'il lit', 'il étudie', 'il prie', 'il dit', 'il analyse', 'il critique',
      ],
      ladders: [
        {
          steps: [
            'Il dirige cette entreprise.',
            'Il dirige cette entreprise qui est située dans la ville de Nice.',
            'Il dirige cette entreprise qui est située dans la ville de Nice et il part en mission pour Venise.',
          ],
          translation: 'Он руководит этим предприятием. → …которое находится в Ницце. → …и уезжает в командировку в Венецию.',
        },
      ],
    },
    {
      id: 'er-final',
      lesson: 2,
      ipa: '[e] · [ɛʁ]',
      title: 'Читается ли -er в конце слова?',
      problem: 'Одно и то же написание -er даёт то [e] (parler), то [ɛʁ] (la mer). Ошибка в обе стороны звучит одинаково грубо.',
      howTo: 'В односложных словах -er произносится полностью: [ɛʁ]. В длинных словах r немая, остаётся [e]. Заимствования из английского и группа исключений сохраняют [ɛʁ].',
      spellings: [
        '[ɛʁ] — односложные: mer, fier, cher, ver',
        '[e] — длинные слова: parler, marcher, passager, dernier, premier, nier',
        '[ɛʁ] — англицизмы: leader, manager, supporter; исключения: hiver, cancer, master, super, amer, hyper',
      ],
      words: [
        'la mer', 'cher', 'hiver', 'boulanger', 'supporter', 'ce passager', "l'appareil ménager",
        "c'est super", 'le leader', 'le poissonnier', 'le boucher', 'le master',
        'le métier', 'premier', 'dernier', 'fier',
      ],
      pairs: [
        { a: 'la mer', b: 'la mère', hint: 'оба [mɛʁ] — различаются только на письме' },
        { a: 'le boucher', b: 'le boulanger', hint: 'оба на [e]: r не читается' },
      ],
      phrases: [
        "Le boucher ouvre le premier, l'horloger ouvre le dernier.",
        'Quel métier vous préférez ? J’aime le métier de policier.',
        'Les supporters adorent ce footballer, il est super !',
        'Cet hiver, les pâtissiers proposent leurs gâteaux aux passagers.',
      ],
    },
    {
      id: 'y-son',
      lesson: 2,
      ipa: '[y]',
      title: 'Звук [y] — язык от «и», губы от «у»',
      problem: 'Русского аналога нет. Обычно выходит либо «у» (tu → «ту»), либо «ю» со смягчением согласной («тю»). Оба варианта — ошибка.',
      howTo: 'Скажите [i] и, не двигая языком, соберите губы в трубочку. Язык остаётся впереди, у нижних зубов. Согласная перед [y] не смягчается.',
      words: [
        'tu fumes', 'tu tues', 'tu parles', 'tu fais', 'la Lune', 'mes études', 'il étudie',
        'plus tard', 'utile', 'utiliser', 'Lucie', 'Luc', 'université', 'Russe', 'la Russie',
      ],
      longWords: ['la luge', 'ce juge', 'la nature', 'la parure', 'la brûlure'],
      phrases: [
        "Luc fait ses études à l'université.",
        'Arthur utilise sa flûte et fait de la musique à Lucie.',
        "Les études à l'université, c'est utile ! C’est sûr !",
        'Tel juge, tel jugement.',
      ],
      twister: "Ursule étudie une multitude d'inutilités.",
    },
    {
      id: 'u-son',
      lesson: 2,
      ipa: '[u]',
      title: 'Звук [u] — глубокое «у»',
      problem: 'Путается с [y]: если губы собраны, а язык остался впереди, вместо [u] выходит [y] — и слово меняется.',
      howTo: 'Губы сильно вытянуты вперёд, язык отодвинут назад и вниз. Это «у» глубже русского.',
      words: [
        'toujours', 'les touristes', 'souvent', 'cousine', 'surtout', 'nous', 'vous',
        'les fours', 'la journée', 'tout', 'toute', 'tous', 'la soupe',
      ],
      longWords: ['pour', 'jour', 'lourd', 'la louve', 'douze'],
      phrases: [
        'Tous les touristes préfèrent cette soupe.',
        'Ces loups et ces louves chassent des hiboux.',
        'Ma cousine est rousse.',
        'La voiture a quatre roues, elle roule dans la rue.',
      ],
      ladders: [
        {
          steps: [
            'Ma cousine est rousse.',
            'Le cou de ma cousine est couvert de taches rousses.',
            "Ma cousine est rousse, elle n'aime pas la cuisine russe.",
          ],
          translation: 'Моя кузина рыжая. → Шея кузины покрыта рыжими веснушками. → …она не любит русскую кухню.',
        },
      ],
    },
    {
      id: 'y-vs-u',
      lesson: 2,
      ipa: '[y] ↔ [u]',
      title: 'Противопоставление [y] и [u] — смена звука меняет слово',
      problem: 'Самая частая пара-ловушка. rousse и russe, pour и pur — разные слова, а на слух русскоязычного они сливаются.',
      howTo: 'Разница только в положении языка: для [y] он впереди, для [u] — сзади. Губы в обоих случаях собраны. Тренируйте парами, не по отдельности.',
      words: ['rousse', 'russe', 'pour', 'pur', 'sourd', 'sur', 'sûr', 'tous', 'tu', 'roue', 'rue'],
      pairs: [
        { a: 'rousse', b: 'russe', hint: 'рыжая ↔ русская' },
        { a: 'pour', b: 'pur', hint: 'для ↔ чистый' },
        { a: 'sourd', b: 'sûr', hint: 'глухой ↔ уверенный' },
        { a: 'tous', b: 'tu', hint: 'все ↔ ты' },
        { a: 'roue', b: 'rue', hint: 'колесо ↔ улица' },
      ],
      phrases: [
        'Ma cousine est dans ma cuisine.',
        'Je me dis souvent : je le fais le jour suivant.',
        "L'étudiant minutieux va à l'université tous les jours.",
        'Ursule et Muriel écoutent de la musique.',
        'Tu as fait tout le travail ?',
        'Nous sommes pour un air pur.',
      ],
    },
    {
      id: 'ui',
      lesson: 2,
      ipa: '[ɥi]',
      title: 'Сочетание UI = [ɥi] — один слитный слог',
      problem: 'Читают в два слога («ну-и»), теряя полугласный [ɥ]. Правильно — единым движением.',
      howTo: 'Начните с позиции [y] (губы трубочкой, язык впереди) и немедленно скользните в [i]. Получается один слог, а не два.',
      words: [
        'puis', 'lui', 'je suis', 'la nuit', 'la cuisine', 'suivant', 'la pluie',
        'minuit', 'suivre', 'ce parapluie', 'les huîtres', 'nuire', 'puis-je', 'fuir', 'luire',
      ],
      phrases: [
        "Et puis, la nuit, c'est la pluie.",
        'Sous ce parapluie, tu vas goûter des huîtres.',
        'Puis-je vous suivre dans votre cuisine ?',
        'À partir du jour suivant, la pluie tombera souvent.',
        'Ma cousine aime la pluie, elle regarde la pluie de la cuisine.',
      ],
    },
  ],
};

export const LESSON_3: PhoneticsLesson = {
  n: 3,
  title: 'Огублённые и открытые/закрытые пары: /ø – œ/, /ə/, /o – ɔ/, /a – ɑ/',
  subtitle: 'Плюс первый носовой звук [ɑ̃]',
  articulation: [
    {
      id: 'art-open-close',
      title: 'Открытый ↔ закрытый: контроль челюсти',
      steps: [
        'Положите ладонь под подбородок.',
        'Произнесите [ø] (deux) — челюсть почти неподвижна.',
        'Произнесите [œ] (sœur) — челюсть заметно опускается в ладонь.',
        'Чередуйте 10 раз: deux — sœur, deux — sœur.',
      ],
      why: 'Закрытые и открытые пары различаются именно раствором рта. Ладонь даёт мгновенную обратную связь: если челюсть не двигается, вы произносите один и тот же звук дважды.',
      seconds: 45,
    },
  ],
  drills: [
    {
      id: 'oe-ferme',
      lesson: 3,
      ipa: '[ø]',
      title: 'Закрытое [ø] — «ё» без йота',
      problem: 'Русскоязычные подставляют «ё» с призвуком [j] в начале либо просто «э». Французский [ø] — чистый огублённый звук.',
      howTo: 'Язык в позиции [e], губы округлены и слегка выдвинуты. Никакого «й» перед звуком.',
      spellings: [
        'eu, œu — последний произносимый звук слова: pneu, bleu, feu, deux, creux, nœud, il veut, il peut',
        'eu перед гласной: bleuâtre',
        'eu перед s между гласными: furieuse, sérieuse',
        'Исключения: neutre, feutre, jeudi, Eugène, meunier',
      ],
      words: [
        'il pleut', 'ces lieux', 'Mathieu', 'sérieux', 'minutieux', 'rigoureux', 'pneu',
        'vieux', 'feutre', 'neutre', 'bleu', 'feu', 'jeu', 'les yeux', 'deux',
      ],
      longWords: ['sérieuse', 'minutieuse', 'rigoureuse'],
      phrases: [
        'Les yeux de Mathieu sont bleus.',
        'La vendeuse brise deux œufs.',
        'Si tu veux, tu peux goûter ce fruit délicieux.',
        'La serveuse est sérieuse et minutieuse.',
        'Jeudi, le vieux fait ses adieux.',
      ],
    },
    {
      id: 'oe-ouvert',
      lesson: 3,
      ipa: '[œ]',
      title: 'Открытое [œ] — шире и ниже',
      problem: 'Произносят вместо него закрытое [ø], и sœur звучит как «сё» вместо «сёр» с широким раствором.',
      howTo: 'Губы округлены, но рот раскрыт шире, челюсть опущена. Появляется перед произносимой согласной.',
      spellings: [
        'eu, œu перед согласными (кроме s между гласными): ils veulent, ils peuvent',
        'ue после c, g: cueillir, accueil, orgueil',
        '-er, -ir, u в заимствованиях: leader, supporter, sir, club, pub',
      ],
      words: ['peuple', 'seul', 'veuf', 'cet œuf', 'ce bœuf', 'jeune', 'immeuble'],
      longWords: ['ma sœur', 'la fleur', 'le directeur', 'le coureur', 'la chaleur', 'une heure', 'la peur', 'les mœurs', 'meilleur'],
      phrases: [
        "Ma sœur n'a pas peur de cueillir des fleurs.",
        'Le coureur court malgré la chaleur.',
        'Le directeur arrive à une heure et demie.',
        'Le serveur est jeune et il est le meilleur.',
        'Qui vole un œuf, vole un bœuf.',
      ],
    },
    {
      id: 'oe-contrast',
      lesson: 3,
      ipa: '[ø] ↔ [œ]',
      title: 'Противопоставление [ø] и [œ] в одном слове',
      problem: 'В словах вроде heureux оба звука стоят рядом — и произносятся одинаково, хотя должны различаться.',
      howTo: 'Правило простое: закрытый [ø] — когда звук последний произносимый; открытый [œ] — когда после него звучит согласная. В heureux: [œ]-[ʁø].',
      words: ['heureux', 'peureux', 'heureusement', 'malheureux', 'malheureusement', 'deux heures', 'neuf œufs'],
      phrases: [
        'Ces serveurs et ces serveuses sont sérieux et travailleurs.',
        "Malheureusement, le directeur ne peut pas être à l'heure.",
        'À deux heures, les voyageurs peuvent déjeuner.',
        'Jeudi, les jeunes acteurs répètent neuf heures.',
        'La jeune coiffeuse est heureuse.',
      ],
    },
    {
      id: 'schwa',
      lesson: 3,
      ipa: '[ə]',
      title: 'Беглое [ə] — звук, который то есть, то нет',
      problem: 'Либо произносят его как полноценное «э», либо выбрасывают там, где он нужен. В беглой речи ритм фразы держится именно на нём.',
      howTo: 'Очень краткий, слабый огублённый звук. В быстрой речи часто выпадает: je le vois → [ʒlə vwa]. Начинайте медленно, с полным [ə], затем ускоряйтесь и позволяйте ему исчезать.',
      words: [
        'lever', 'la leçon', 'le samedi', 'je le vois', 'il me le donne',
        'la fenêtre', 'vous serez', 'vous seriez', 'vous ferez', 'vous feriez',
        'cet atelier', 'notre leçon', "l'autre jour",
      ],
      phrases: [
        'Samedi, il y a quatre leçons de langue française.',
        'Malheureusement, le gouvernement ne le fait pas.',
        "Elle parle vite et nous ne comprenons pas ce qu'elle dit.",
        'Je te le montre demain, ce film, tu me dis si tu es libre.',
        'Au revoir, je te vois demain, tu me téléphones ce soir !',
        'Nous faisons ce travail depuis quatre mois.',
      ],
    },
    {
      id: 'mix-yu-oe',
      lesson: 3,
      ipa: '[y] · [u] · [ø] · [œ] · [ə]',
      title: 'Сводная тренировка огублённых',
      problem: 'По отдельности звуки получаются, а в потоке речи сваливаются в один «средний» звук.',
      howTo: 'Читайте медленно, сознательно меняя положение губ и языка на каждом звуке. Затем ускоряйтесь, сохраняя различия.',
      words: [
        'méticuleux', 'rigoureux', 'douloureux', 'curieux', 'furieux', 'talentueux', 'Moscou',
        'amoureux', 'boueux', 'joueur', 'aucune', 'méticuleuse', 'rigoureuse', 'douloureuse',
        'curieuse', 'furieuse', 'talentueuse', 'amoureuse', 'boueuse', 'joueuse',
      ],
      phrases: [
        'Les Russes sont amoureux de Moscou, une ville curieuse.',
        'La coiffeuse méticuleuse et rigoureuse est amoureuse.',
        'Les joueurs et les joueuses jouent méticuleusement.',
        "Pour arriver à Moscou, ne prenez pas cette rue boueuse.",
        'La cuisine est sale, ma cousine est furieuse.',
        'Cette danseuse talentueuse est amoureuse de ce danseur.',
      ],
    },
    {
      id: 'o-ferme',
      lesson: 3,
      ipa: '[o]',
      title: 'Закрытое [o]',
      problem: 'Русское «о» безударное редуцируется в «а» (мо-ло-ко → «малако»). Во французском редукции нет вообще.',
      howTo: 'Губы плотно округлены и выдвинуты, звук напряжённый. Никакого «а» вместо «о» — даже в безударном слоге.',
      spellings: [
        'o в конце слова: micro, métro, boulot',
        'au (кроме перед r), eau: Claude, faute, mauve, bureau',
        'ô: drôle, pôle',
      ],
      words: [
        'Claude', 'Claudine', 'le métro', 'le dos', 'le micro', 'le château',
        "l'oiseau", 'Bordeaux', 'il est beau', 'ce tableau', 'ce manteau',
      ],
      longWords: ['la cause', 'la rose', 'la dose', 'la pause', 'il pose'],
      phrases: [
        "Claude saute dans l'eau de ce bateau.",
        'Claudine propose de goûter ce beau gâteau.',
        'Rose ne propose aucune chose sérieuse.',
        "Pauline se repose avec Hugo, c'est drôle.",
      ],
    },
    {
      id: 'o-ouvert',
      lesson: 3,
      ipa: '[ɔ]',
      title: 'Открытое [ɔ]',
      problem: 'Смешивается с закрытым [o]: pomme произносят как «пом» с узким «о» вместо широкого.',
      howTo: 'Рот раскрыт шире, губы округлены слабее. Появляется в середине слова и в au перед r.',
      spellings: [
        'o в середине слова, не в конце: école, cloche, poche',
        'au перед r: aurore, Laure, j’aurai',
      ],
      words: [
        'bonne', 'elle sonne', 'téléphone', 'microphone', 'Yvonne', 'cet homme',
        'une école', 'une pomme', 'des bottes', 'le col', "l'alcool",
      ],
      longWords: ["l'aurore", 'Laure', 'sort', 'le port', 'une éloge', "d'accord"],
      phrases: [
        "Yvonne sonne à la porte de l'école de Nicole.",
        'Le téléphone sonne et je décroche pour papoter.',
        'Cet homme est économe, il achète des carottes.',
        'Simone donne la pomme à la bonne de Laure.',
        'Nicole s’approche du microphone et commence à parler.',
        "Laure somnole tout le soir et elle s'endort très vite.",
      ],
    },
    {
      id: 'o-contrast',
      lesson: 3,
      ipa: '[o] ↔ [ɔ]',
      title: 'Противопоставление [o] и [ɔ]',
      problem: 'В одном слове часто соседствуют оба: monotone, protocole. Нужен сознательный переход.',
      howTo: 'Следите за раствором рта: закрытый [o] — узкий, открытый [ɔ] — широкий. Челюсть работает.',
      words: [
        'la moto', 'le taureau', 'le bistrot', 'dodo', 'protocole', 'monocle',
        'monotone', 'le métro', "l'aube", "l'aurore", 'la baume',
      ],
      phrases: [
        'Claude et Hugo sautent autour de la moto.',
        "Aucune porte n'est ouverte à l'aube.",
        'Le téléphone d’Yvonne sonne trop tôt.',
        'Le couteau de Paul est perdu, quel problème !',
        "Métro, boulot, dodo, c'est la vie de l'homme moderne.",
        "Le poète dit ses vers d'une voix monotone.",
        'Où vas-tu ? Je vais au Canada et au Mexique.',
      ],
    },
    {
      id: 'a-anterieur-posterieur',
      lesson: 3,
      ipa: '[a] ↔ [ɑ]',
      title: 'A переднего и заднего ряда',
      problem: 'Различие тонкое и в современной речи стирается, но в châsse/tache, pâle/palle оно ещё держится и придаёт речи естественность.',
      howTo: '[a] переднего ряда — обычное, язык впереди. [ɑ] заднего ряда — глубже, язык отодвинут: â, а также a перед -s, -z, -ss и в суффиксе -ation.',
      spellings: [
        '[a]: a в любом положении, кроме перед -s, -z, -ss',
        '[ɑ]: â (château, pâle, tâche); a перед -s, -z (masse, basse, bas); -ation (association)',
        'Исключения: paille, mois, toit, foie',
      ],
      words: [
        'pâle', 'château', 'bas', 'passer', 'nation', 'déclamation', 'association',
        'le mois', 'le toit', 'le foie', 'la tâche',
      ],
      longWords: ['le Havre', 'base', 'topaze', 'la paille', 'hélas', 'masse', 'basse', 'grâce'],
      phrases: [
        'Derrière la glace, elle est lasse et pâle.',
        'La classe de Thomas est basse.',
        'La lune est pâle et jaunâtre.',
        'Qui trop se hâte, reste en chemin.',
        'Hélas, les lilas de Cléopâtre sont rougeâtres.',
      ],
    },
    {
      id: 'nasal-a',
      lesson: 3,
      ipa: '[ɑ̃]',
      title: 'Носовой [ɑ̃] — an, am, en, em',
      problem: 'Произносят «ан» с чётким согласным [n] на конце. Во французском n/m НЕ произносится — она лишь делает гласный носовым.',
      howTo: 'Откройте рот как для [ɑ] и направьте струю воздуха через нос, НЕ смыкая язык с нёбом. Проверка: зажмите нос — звук должен заметно измениться. Если не меняется, вы произносите обычное «а».',
      spellings: ['an, am, en, em в закрытом слоге'],
      words: [
        'la France', 'le français', 'en mangeant', 'en parlant', 'des enfants', 'lentement',
        'cet ensemble', 'avant', 'moment', 'la science', 'ce récipient', "l'anglais", "l'allemand", 'Allemagne',
      ],
      phrases: [
        'Henri et André marchent lentement en regardant le ciel.',
        "J'entends André et Armand qui chantent dans la chambre.",
        'Nous mangeons le dimanche chez notre tante Armande.',
        'La lampe dans la chambre des enfants est grande.',
        'Armand, je t’entends, va-t-en, car ta tante t’attend !',
      ],
    },
  ],
};
