// Уроки 4–5: оставшиеся носовые, полугласный [w], особые случаи чтения,
// связывание (liaison) и трудные слова. Материал — конспекты уроков 4 и 5.

import type { PhoneticsLesson } from './corpusTypes';

export const LESSON_4: PhoneticsLesson = {
  n: 4,
  title: 'Носовые [ɔ̃] и [ɛ̃], полугласный [w], особые случаи чтения',
  subtitle: 'Плюс связывание: обязательное, запрещённое и факультативное',
  articulation: [
    {
      id: 'art-nose',
      title: 'Проверка носовых: зажми нос',
      steps: [
        'Произнесите bon [bɔ̃], зажав пальцами нос.',
        'Звук должен резко измениться и «упереться» — значит воздух шёл через нос правильно.',
        'Если звук не изменился, вы произносите обычное «о» с добавленным «н».',
        'Повторите с bonne [bɔn] — здесь при зажатом носе звук НЕ меняется. Почувствуйте разницу.',
      ],
      why: 'Носовой и обычный гласный различают слова: bon ↔ bonne, un ↔ une. Зажатый нос — самый быстрый способ проверить себя без преподавателя.',
      seconds: 45,
    },
  ],
  drills: [
    {
      id: 'nasal-o',
      lesson: 4,
      ipa: '[ɔ̃]',
      title: 'Носовой [ɔ̃] — on, om',
      problem: 'Добавляют согласный [n] в конце: «бон» вместо [bɔ̃]. Носовой гласный — это один звук, а не два.',
      howTo: 'Губы округлены как для [o], воздух идёт через нос, кончик языка не касается нёба. Никакого [n] после гласного.',
      spellings: ['on, om в закрытом слоге'],
      words: [
        'mon tonton', 'bonbon', 'balcon', 'pigeon', 'mon nom', 'ton prénom',
        'cette chanson', 'ce pont', 'ce blond', 'ce bon garçon', 'la montre',
      ],
      pairs: [
        { a: 'bon', b: 'bonne', hint: 'носовой [bɔ̃] ↔ обычный [bɔn]: удвоенная n «убивает» назальность' },
        { a: 'son', b: 'sonne', hint: 'то же противопоставление' },
      ],
      phrases: [
        'Quel est ton nom et ton prénom, mon garçon ?',
        'Mon tonton Simon est grand, blond et rond.',
        'Suzon gronde son garçon qui a perdu son crayon.',
        "Les plongeurs plongent au fond de l'océan.",
        'Pendant la récréation Gaston mange son grand bonbon.',
        "Sur le pont d'Avignon on y danse tous en rond.",
      ],
    },
    {
      id: 'nasal-e',
      lesson: 4,
      ipa: '[ɛ̃]',
      title: 'Носовой [ɛ̃] — in, ain, ein, ien',
      problem: 'Произносят «ин» или «эн» с согласной. А ещё путают с [ɑ̃]: important содержит оба носовых подряд.',
      howTo: 'Рот раскрыт шире, чем для [ɔ̃], губы не округлены, воздух через нос. В сочетании ien сначала звучит [j]: bien = [bjɛ̃].',
      spellings: ['in, im, ain, ein, ien, yn, ym; -en в некоторых словах (examen, agenda)'],
      words: [
        'important', 'enfin', 'bien', 'rien', 'lien', 'mon cousin', 'Alain', 'Martin',
        'américain', 'mécanicien', 'musicien', 'le médecin', 'examen', 'agenda', 'plein', 'coin',
      ],
      pairs: [
        { a: 'important', b: 'impossible', hint: 'в important два разных носовых: [ɛ̃] и [ɑ̃]' },
        { a: 'brin', b: 'brun', hint: 'исторически [ɛ̃] ↔ [œ̃]; в современной речи часто совпадают' },
      ],
      phrases: [
        'Mon cousin Alain est un vieux marin.',
        'Tout est bien qui finit bien.',
        "L'accident contraint le mécanicien à actionner le frein du train.",
        'Le gardien vient chez Lucien mais il ne dit rien.',
        'Chaque matin, le petit Martin donne du pain à ses lapins.',
        'Parmi mes copains, il y a des musiciens et des médecins.',
        'Tiens, à malin — malin et demi ! — dit Julien à Benjamin.',
      ],
    },
    {
      id: 'w-semivoyelle',
      lesson: 4,
      ipa: '[w]',
      title: 'Полугласный [w] — oi, ou + гласный',
      problem: 'Читают в два слога: «лу-э» вместо louer [lwe]. Полугласный должен слиться со следующим гласным в один слог.',
      howTo: 'Начните с позиции [u] (губы трубочкой) и сразу скользните к следующему гласному, не задерживаясь. oi = [wa], а не «ой».',
      spellings: ['oi = [wa]', 'ou + гласный = [w]', 'oy = [waj]'],
      words: [
        'jouer', 'louer', 'clouer', 'une girouette', 'Louis', 'trois fois', 'Benoît',
        'le soir', 'une mouette', 'une brouette', 'une coiffure', 'une voiture',
        'elle est chouette', "de l'ouate", 'un jouet', 'une boisson', 'Louise', 'le loyer',
      ],
      phrases: [
        'Louis dit : allons louer cette maison avec une girouette !',
        'Louise aime jouer avec ses jouets.',
        'Les coiffures des Rouennaises sont éblouissantes.',
        'François habite tout près de chez moi.',
        'Pour louer une maison il faut présenter trois documents.',
        'Voici mes jouets, ils sont chouettes !',
      ],
    },
    {
      id: 'cas-particuliers',
      lesson: 4,
      ipa: 'y · im/in · -ill- · -um · ex-',
      title: 'Особые случаи чтения',
      problem: 'Каждая группа — источник системных ошибок: ville читают как «вий», examen как «экзамен», forum как «форюм».',
      howTo: 'Разберите группы по одной и заучите ключевые слова-образцы — они закрывают большинство случаев.',
      spellings: [
        'y = [i]: stylo, symphonie, cyprès, hymne',
        'y между гласными = [i]+[j]: pays (pai-i), crayon (crai-ion), voyage, royal, employer, envoyer, essuyer, payer, essayer',
        'im-, in- + согласная = носовой: important, involontaire, inspecteur, introduire, instituteur, imposer, indulgent, insolent',
        'in-, im- + гласная или двойная = [i]+[n]: inoubliable, inactif, inutile, immobile, immortel, innovation, immunité',
        '-ue- после c, g = [œ]: accueillir, cueillir, accueil, orgueil',
        '-um = [ɔm]: forum, maximum, minimum, album, sérum. НО parfum = [paʁfœ̃]',
        '-ill- = [ij]: fille, grille, famille, quille, bille, gentille, feuille, bouillon, mouillé, nouilles',
        '-ill- = [il] (исключения): mille, million, ville, village, villageois, tranquille, tranquillité',
        'ex- = [egz] перед гласной: examen, exercice, exercer, exigu. ex- = [eks] перед согласной: taxi, expliquer, expression, exposer',
        'Monsieur = [məsjø], Messieurs = [mesjø]',
      ],
      words: [
        'stylo', 'symphonie', 'hymne', 'pays', 'crayon', 'voyage', 'royaume', 'employer', 'essuyer', 'payer',
        'important', 'inspecteur', 'instituteur', 'indulgent', 'inoubliable', 'inutile', 'immobile', 'immortel',
        'accueillir', 'cueillir', 'orgueil', 'forum', 'maximum', 'album', 'parfum',
        'fille', 'famille', 'gentille', 'feuille', 'bouillon', 'nouilles',
        'mille', 'million', 'ville', 'village', 'tranquille', 'juillet', 'cuillère',
        'examen', 'exercice', 'taxi', 'expliquer', 'expression', 'Monsieur', 'Messieurs',
      ],
      pairs: [
        { a: 'ville', b: 'fille', hint: '[vil] ↔ [fij] — одно написание -ill-, разное чтение' },
        { a: 'tranquille', b: 'quille', hint: '[tʁɑ̃kil] ↔ [kij]' },
        { a: 'examen', b: 'expliquer', hint: 'ex- = [egz] перед гласной ↔ [eks] перед согласной' },
      ],
      twister: 'Il pleut, il mouille, c’est la fête à la grenouille ; il fait beau temps, c’est la fête au paysan.',
    },
    {
      id: 'liaison-obligatoire',
      lesson: 4,
      ipa: 'liaison',
      title: 'Обязательное связывание',
      problem: 'Без связывания речь звучит рублено и «по-учебниковому». А ещё связывание меняет звук: s → [z], d → [t], x → [z], f → [v].',
      howTo: 'Немая конечная согласная «оживает» и переходит в следующий слог перед гласной. Связывание обязательно внутри тесных групп: определитель + существительное, местоимение + глагол, односложный предлог, très.',
      spellings: [
        's → [z] · d → [t] · x → [z] · f → [v]',
        'Определитель + существительное: mes amis, bons élèves, tes oncles, deux heures, neuf ans, grand amour, ces amis',
        'Местоимение + глагол: ils ont, elles habitent, vous êtes, ils aiment, nous habitons, il les aime, vas-y, prends-en',
        'Односложный предлог: dans un restaurant, chez un ami, dans une école',
        'très: très aimable, très intelligent, très ouvert',
        'c’est / il est: il est évident, il est étudiant',
      ],
      words: [
        'mes amis', 'bons élèves', 'tes oncles', 'ses amis', 'deux heures', 'neuf ans', 'neuf heures',
        'dix heures', 'grand amour', 'ces amis', 'ils ont', 'elles habitent', 'vous êtes', 'ils aiment',
        'elles adorent', 'nous habitons', 'il les aime', 'elle les adore', 'nous les achetons',
        'vas-y', 'penses-y', 'prends-en', 'profites-en',
        'dans un restaurant', 'chez un ami', 'dans une école',
        'très aimable', 'très intelligent', 'très ouvert',
        'petit à petit', 'c’est-à-dire', 'sous-entendu', 'aux États-Unis', 'de temps en temps',
        'tout à l’heure', 'avant-hier', 'tout à fait', 'tout à coup', 'les Champs-Élysées', 'plus ou moins',
        'il est évident', 'il est étudiant', 'huit ans',
      ],
      exceptions: [
        'В инверсии связывания нет: Ont-ils / acheté ? Ont-elles / aimé ?',
        'Иногда связывается предпоследняя буква r: nord-ouest, nord-est, vers une heure.',
        'После r связывается s в словах leurs, plusieurs, divers: leurs enfants, plusieurs entreprises, divers articles.',
      ],
    },
    {
      id: 'liaison-interdite',
      lesson: 4,
      ipa: 'liaison ✗',
      title: 'Запрещённое связывание',
      problem: 'Ученики, освоив liaison, начинают связывать везде — и это ошибка не меньшая, чем её отсутствие.',
      howTo: 'Запомните ключевые запреты: после существительного-подлежащего, между существительным и следующим прилагательным, после et, перед h aspiré, перед huit и onze, после вопросительных quand, comment, combien.',
      spellings: [
        'После знаменательного слова перед предлогом: Ce sont des affaires / à emporter.',
        'Между существительным и стоящим после него прилагательным: un enfant / obéissant.',
        'Подлежащее-существительное + глагол: L’enfant / allait / à l’école.',
        'Глагол + дополнение: Je viens / avec mon frère. НО с être связывание есть: Je suis étudiant.',
        'После союза et: Marie et / Anne. Et / il a dit…',
        'После alors: Alors, / elle est arrivée ?',
        'В инверсии сложных времён: Sont-ils / arrivés ?',
        'Внутри составных слов во мн. ч.: des arcs / -en-ciel, des machines / à laver.',
        'Перед h aspiré: des / héros, des / haricots, le / héros.',
        'Перед словами на [j]: yacht, yak, yaourt, yen, whisky.',
        'Перед huit и onze: mes / onze chiens, mes / huit chats. НО внутри чисел связывание есть: dix-huit, vingt-huit.',
        'После quand, comment, combien: Comment / ont-ils fait ça ? Исключение: Comment allez-vous ?',
      ],
      words: [
        'des héros', 'des haricots', 'le héros', 'le haricot',
        'Marie et Anne', 'un enfant obéissant', 'des arcs-en-ciel', 'des machines à laver',
        'mes onze chiens', 'mes huit chats', 'dix-huit', 'vingt-huit', 'vingt-et-un',
        'Je suis étudiant', 'Nous avons une voiture', 'Mais il part aujourd’hui', 'mais oui',
      ],
      pairs: [
        { a: 'Quand elle viendra ?', b: 'Quand elle viendra, je lui parlerai.', hint: 'вопросительное слово — без связывания; союз — со связыванием' },
        { a: 'Comment allez-vous ?', b: 'Comment ont-ils fait ?', hint: 'устойчивая формула со связыванием ↔ обычный вопрос без него' },
      ],
    },
    {
      id: 'liaison-facultative',
      lesson: 4,
      ipa: 'liaison ~',
      title: 'Факультативное связывание',
      problem: 'Здесь нет «правильно» и «неправильно» — есть регистр речи. Чем больше связываний, тем официальнее звучит речь.',
      howTo: 'Всё, что не попало в обязательные и запрещённые, — на ваш выбор. В официальной обстановке связывайте, в бытовой можно опускать.',
      spellings: [
        'После наречий: trop aimable, vraiment aimable, j’ai beaucoup aimé',
        'После pas, point, plus: il n’a pas appris la poésie',
        'После многосложных предлогов: après avoir lu le livre',
        'Вспомогательный глагол + причастие: elles sont arrivées',
        'Существительное + прилагательное во мн. ч.: des articles intéressants',
      ],
      words: [
        'trop aimable', 'vraiment aimable', 'j’ai beaucoup aimé',
        'il n’a pas appris', 'après avoir lu', 'elles sont arrivées', 'des articles intéressants',
      ],
    },
  ],
};

export const LESSON_5: PhoneticsLesson = {
  n: 5,
  title: 'Тонкости: tous, -il, en-/em-, трудные слова',
  subtitle: 'Финальная шлифовка — случаи, где ошибаются даже продвинутые',
  articulation: [
    {
      id: 'art-speed',
      title: 'Разгон: от медленного к беглому',
      steps: [
        'Возьмите любую фразу из курса и прочитайте её втрое медленнее обычного, проговаривая каждый звук.',
        'Прочитайте вдвое медленнее — сохраняя все различия звуков.',
        'Прочитайте в нормальном темпе.',
        'Прочитайте быстро — и проверьте, не потерялись ли носовые и огублённые.',
      ],
      why: 'Принцип из первого урока: произнесение звуков — это движение мышц, как танец. Сначала медленно и поэтапно, только потом на скорости. Обратный порядок закрепляет ошибку.',
      seconds: 90,
    },
  ],
  drills: [
    {
      id: 'tous',
      lesson: 5,
      ipa: '[tu] ↔ [tus]',
      title: 'Tous: когда s читается, а когда нет',
      problem: 'Читают одинаково во всех случаях. А различие смысловое: tous-определитель и tous-местоимение звучат по-разному.',
      howTo: 'Перед существительным (tous les étudiants) s НЕ читается — [tu]. Если tous стоит самостоятельно, замещая существительное (Tous sont venus), s читается — [tus].',
      words: [
        'tous les étudiants', 'tous les amis', 'tous mes parents', 'tous mes copains',
        'tous ces musées', 'tous les jours', 'tous les samedis',
      ],
      pairs: [
        { a: 'Tous les étudiants sont venus.', b: 'Tous sont venus.', hint: '[tu] перед существительным ↔ [tus] самостоятельно' },
        { a: 'Tous les exercices sont difficiles.', b: 'Tous font de la gymnastique.', hint: 'то же различие' },
      ],
      phrases: [
        'Tous sont venus.',
        'Tous regardent la télé.',
        'Tous veulent partir.',
        'Tous disent leur nom.',
        'Tous apprennent le français.',
        'Tous les matins il fait de la gymnastique.',
        'Tous font de la gymnastique.',
        'Tous finissent le travail.',
        'Tous les exercices sont difficiles.',
        'Tous les livres sont intéressants.',
        'Tous sont à la bibliothèque.',
      ],
    },
    {
      id: 'final-il',
      lesson: 5,
      ipa: '-il',
      title: 'Конечное -il: читается или молчит',
      problem: 'Нет единого правила — только группы слов. Ошибка звучит грубо: gentil как «жантиль».',
      howTo: 'В одних словах l произносится, в других — нет. Заучивайте парами-образцами.',
      spellings: [
        'l произносится: cil, sourcil, il, viril, péril',
        'l молчит: gentil, fusil, outil',
      ],
      words: ['cil', 'sourcil', 'il', 'viril', 'péril', 'gentil', 'fusil', 'outil'],
      pairs: [
        { a: 'péril', b: 'outil', hint: '[peʁil] — l звучит ↔ [uti] — l молчит' },
        { a: 'viril', b: 'gentil', hint: 'то же противопоставление' },
      ],
    },
    {
      id: 'en-em',
      lesson: 5,
      ipa: 'en- · em-',
      title: 'Коварные en-, em- и удвоенные согласные',
      problem: 'femme читают как «фем» с носовым, différemment — по буквам. Здесь написание обманывает.',
      howTo: 'В femme и наречиях на -emment сочетание em/en даёт [a], а не носовой: femme = [fam], différemment = [difeʁamɑ̃]. Удвоенная согласная снимает назальность: immortel = [imɔʁtɛl].',
      words: [
        'femme', 'différemment', 'immortel', 'innombrable', 'solennel', 'antenne',
        'enneiger', 'emmener', 'emménager', 'ennuyer',
      ],
      pairs: [
        { a: 'femme', b: 'flamme', hint: 'оба с [a], но femme пишется через e' },
        { a: 'immortel', b: 'important', hint: 'удвоенная m — назальности нет ↔ одиночная m + согласная — носовой' },
      ],
    },
    {
      id: 'mots-difficiles',
      lesson: 5,
      ipa: '⚠︎',
      title: 'Трудные слова — выучить наизусть',
      problem: 'Слова, где нет правила: их просто нужно запомнить. Именно на них чаще всего спотыкаются.',
      howTo: 'Прослушайте, повторите вслух по три раза каждое, затем в составе фразы.',
      words: [
        'médecin', 'médecine', 'aiguille', 'guerre', 'juillet', 'cuillère',
        'il y en a', "il n'y en a pas", 'mon ami',
      ],
      phrases: [
        'Le médecin étudie la médecine.',
        'En juillet, il prend une cuillère et une aiguille.',
        "Il y en a beaucoup, mais il n'y en a pas assez.",
      ],
    },
  ],
};
