/*
 Generated by typeshare 1.13.4
*/

export interface AIAnalyzeRequest {
	content: string;
	userObjective: string;
}

export interface AIGenerateRequest {
	setId: string;
	exerciseCount: number;
}

export interface AIGradeRequest {
	setId: string;
	cardId: string;
	questionType: string;
	userAnswer: string;
	questionText: string;
}

export interface AIGradeResponse {
	isCorrect: boolean;
	score: number;
	explanation: string;
	correctAnswer: string;
}

export interface AddSetToFolderRequest {
	setId: string;
}

export interface AuthRequest {
	email: string;
	password: string;
}

export interface CardProgress {
	flashcardId: string;
	state: number;
}

export interface ChatMessage {
	role: string;
	content: string;
}

export interface CreateFlashcardRequest {
	term: string;
	definition: string;
	imageUrl?: string;
	fieldsData: Record<string, unknown>;
}

export interface CreateFolderRequest {
	name: string;
	description?: string;
}

export interface CreateSetRequest {
	title: string;
	description?: string;
	isPublic: boolean;
	fieldsSchema: Record<string, unknown>;
	flashcards: CreateFlashcardRequest[];
}

export interface FSRSRatingRequest {
	flashcardId: string;
	rating: number;
	now?: string;
}

export interface FlashcardProgressRequest {
	flashcardId: string;
	isKnown: boolean;
}

export interface FlashcardResponse {
	id: string;
	term: string;
	definition: string;
	imageUrl?: string;
	orderIndex: number;
	fieldsData: Record<string, unknown>;
}

export interface SetSummaryResponse {
	id: string;
	title: string;
	description?: string;
	fieldsSchema: Record<string, unknown>;
	flashcardCount: number;
	createdAt: string;
}

export interface FolderResponse {
	id: string;
	name: string;
	description?: string;
	createdAt: string;
	sets: SetSummaryResponse[];
}

export interface FolderSummaryResponse {
	id: string;
	name: string;
	description?: string;
	setCount: number;
	createdAt: string;
}

export interface GoogleAuthRequest {
	email: string;
	firstName: string;
	lastName?: string;
	avatarUrl?: string;
}

export interface OnboardingRequest {
	dateOfBirth: string;
}

export interface QChatRequest {
	messages: ChatMessage[];
}

export interface ReviewLogResponse {
	state: number;
	due: string;
	scheduledDays: number;
	elapsedDays: number;
}

export interface RoleSelectionRequest {
	role: string;
}

export interface SetProgressResponse {
	totalCards: number;
	knownCards: number;
	masteryPercentage: number;
	cards: CardProgress[];
}

export interface SetResponse {
	id: string;
	title: string;
	description?: string;
	creatorId: string;
	fieldsSchema: Record<string, unknown>;
	flashcards: FlashcardResponse[];
}

export interface StudySessionRequest {
	setId: string;
	progressUpdates: FlashcardProgressRequest[];
}

export interface UpdateFlashcardRequest {
	id?: string;
	term: string;
	definition: string;
	imageUrl?: string;
	fieldsData: Record<string, unknown>;
}

export interface UpdateSetRequest {
	title: string;
	description?: string;
	isPublic: boolean;
	fieldsSchema: Record<string, unknown>;
	flashcards: UpdateFlashcardRequest[];
}

export interface UserProfile {
	id: string;
	firstName: string;
	createdAt: string;
}

export interface UserResponse {
	id: string;
	email: string;
	role: string;
}

