/*
 Generated by typeshare 1.13.4
*/

export interface UserProfile {
	id: string;
	firstName: string;
	createdAt: string;
}

export interface Flashcard {
	id: string;
	term: string;
	definition: string;
	orderIndex: number;
}

export interface StudySet {
	id: string;
	title: string;
	description: string | null;
	flashcards: Flashcard[];
}

export interface CreateFlashcardRequest {
	term: string;
	definition: string;
}

export interface CreateSetRequest {
	title: string;
	description?: string;
	isPublic: boolean;
	flashcards: CreateFlashcardRequest[];
}

export interface FlashcardProgressRequest {
    flashcardId: string;
    isKnown: boolean;
}

export interface StudySessionRequest {
    setId: string;
    progressUpdates: FlashcardProgressRequest[];
}

export interface SetProgressResponse {
    totalCards: number;
    knownCards: number;
    masteryPercentage: number;
}
