/*
 Generated by typeshare 1.13.4
 (Manually updated for Custom Fields)
*/

export type FieldType = 'text' | 'image' | 'audio' | 'math';
export type FieldSide = 'front' | 'back';

export interface FieldSettings {
	language?: string;
	ttsEnabled?: boolean;
	ttsVoice?: string;
	[key: string]: any;
}

export interface FieldSchema {
	id: string;
	name: string;
	type: FieldType;
	side: FieldSide;
	order: number;
	settings: FieldSettings;
}

export type FieldData = Record<string, any>;

export interface AddSetToFolderRequest {
	setId: string;
}

export interface AuthRequest {
	email: string;
	password: string;
}

export interface ChatMessage {
	role: string;
	content: string;
}

export interface CreateFlashcardRequest {
	term: string;
	definition: string;
	imageUrl?: string;
	fieldsData: FieldData;
}

export interface CreateFolderRequest {
	name: string;
	description?: string;
}

export interface CreateSetRequest {
	title: string;
	description?: string;
	isPublic: boolean;
	fieldsSchema: FieldSchema[];
	flashcards: CreateFlashcardRequest[];
}

export interface FlashcardProgressRequest {
	flashcardId: string;
	isKnown: boolean;
}

export interface FlashcardResponse {
	id: string;
	term: string;
	definition: string;
	imageUrl?: string;
	orderIndex: number;
	fieldsData: FieldData;
}

export interface SetSummaryResponse {
	id: string;
	title: string;
	description?: string;
	fieldsSchema: FieldSchema[];
	flashcardCount: number;
	createdAt: string;
}

export interface FolderResponse {
	id: string;
	name: string;
	description?: string;
	createdAt: string;
	sets: SetSummaryResponse[];
}

export interface FolderSummaryResponse {
	id: string;
	name: string;
	description?: string;
	setCount: number;
	createdAt: string;
}

export interface OnboardingRequest {
	dateOfBirth: string;
}

export interface QChatRequest {
	messages: ChatMessage[];
}

export interface RoleSelectionRequest {
	role: string;
}

export interface SetProgressResponse {
	totalCards: number;
	knownCards: number;
	masteryPercentage: number;
}

export interface SetResponse {
	id: string;
	title: string;
	description?: string;
	fieldsSchema: FieldSchema[];
	flashcards: FlashcardResponse[];
}

export interface StudySessionRequest {
	setId: string;
	progressUpdates: FlashcardProgressRequest[];
}

export interface UpdateFlashcardRequest {
	id?: string;
	term: string;
	definition: string;
	imageUrl?: string;
	fieldsData: FieldData;
}

export interface UpdateSetRequest {
	title: string;
	description?: string;
	isPublic: boolean;
	fieldsSchema: FieldSchema[];
	flashcards: UpdateFlashcardRequest[];
}

export interface UserProfile {
	id: string;
	firstName: string;
	createdAt: string;
}

export interface UserResponse {
	id: string;
	email: string;
	role: string;
}

