import type { IrregularVerb } from './types';

/**
 * Школьная таблица 3ème, 125 глаголов, 5 страниц — перенесена дословно со
 * скана. Проверялась по меткам «5, 10, 15…125», которые в оригинале стоят
 * справа от перевода: они защищают от сдвига на строку при переносе.
 *
 * Страницы у Дамира не выходят ровными двадцатипятками (23/26/25/25/26) —
 * это так в самой бумаге, не опечатка при переносе.
 */
export const VERBS: IrregularVerb[] = [
  // Страница 1: BE (1) … COME (23).
  { n: 1, inf: 'BE', pret: 'WAS, WERE', pp: 'BEEN', fr: 'ÊTRE', page: 1 },
  { n: 2, inf: 'BEAT', pret: 'BEAT', pp: 'BEATEN', fr: 'BATTRE', page: 1 },
  { n: 3, inf: 'BEAR', pret: 'BORE', pp: 'BORNE', fr: 'PORTER, SUPPORTER', page: 1 },
  { n: 4, inf: 'BECOME', pret: 'BECAME', pp: 'BECOME', fr: 'DEVENIR', page: 1 },
  { n: 5, inf: 'BEGIN', pret: 'BEGAN', pp: 'BEGUN', fr: 'COMMENCER', page: 1 },
  { n: 6, inf: 'BEND', pret: 'BENT', pp: 'BENT', fr: 'PLIER, (SE) COURBER', page: 1 },
  { n: 7, inf: 'BET', pret: 'BET', pp: 'BET', fr: 'PARIER', page: 1 },
  { n: 8, inf: 'BIND', pret: 'BOUND', pp: 'BOUND', fr: 'LIER', page: 1 },
  { n: 9, inf: 'BITE', pret: 'BIT', pp: 'BITTEN', fr: 'MORDRE', page: 1 },
  { n: 10, inf: 'BLEED', pret: 'BLED', pp: 'BLED', fr: 'SAIGNER', page: 1 },
  { n: 11, inf: 'BLOW', pret: 'BLEW', pp: 'BLOWN', fr: 'SOUFFLER, SE MOUCHER, EXPLOSER', page: 1 },
  { n: 12, inf: 'BREAK', pret: 'BROKE', pp: 'BROKEN', fr: 'CASSER', page: 1 },
  { n: 13, inf: 'BRING', pret: 'BROUGHT', pp: 'BROUGHT', fr: 'APPORTER', page: 1 },
  { n: 14, inf: 'BROADCAST', pret: 'BROADCAST', pp: 'BROADCAST', fr: 'DIFFUSER, ÉMETTRE', page: 1 },
  { n: 15, inf: 'BUILD', pret: 'BUILT', pp: 'BUILT', fr: 'CONSTRUIRE', page: 1 },
  { n: 16, inf: 'BURN', pret: 'BURNT/-ED', pp: 'BURNT/-ED', fr: 'BRÛLER', page: 1 },
  { n: 17, inf: 'BURST', pret: 'BURST', pp: 'BURST', fr: 'ÉCLATER', page: 1 },
  { n: 18, inf: 'BUY', pret: 'BOUGHT', pp: 'BOUGHT', fr: 'ACHETER', page: 1 },
  { n: 19, inf: 'CAN', pret: 'COULD', pp: 'COULD', fr: 'POUVOIR', page: 1 },
  { n: 20, inf: 'CAST', pret: 'CAST', pp: 'CAST', fr: 'LANCER', page: 1 },
  { n: 21, inf: 'CATCH', pret: 'CAUGHT', pp: 'CAUGHT', fr: 'ATTRAPER', page: 1 },
  { n: 22, inf: 'CHOOSE', pret: 'CHOSE', pp: 'CHOSEN', fr: 'CHOISIR', page: 1 },
  { n: 23, inf: 'COME', pret: 'CAME', pp: 'COME', fr: 'VENIR', page: 1 },

  // Страница 2: COST (24) … HAVE (49).
  { n: 24, inf: 'COST', pret: 'COST', pp: 'COST', fr: 'COÛTER', page: 2 },
  { n: 25, inf: 'CUT', pret: 'CUT', pp: 'CUT', fr: 'COUPER', page: 2 },
  { n: 26, inf: 'DEAL', pret: 'DEALT', pp: 'DEALT', fr: 'DISTRIBUER', page: 2 },
  { n: 27, inf: 'DIG', pret: 'DUG', pp: 'DUG', fr: 'CREUSER', page: 2 },
  { n: 28, inf: 'DO', pret: 'DID', pp: 'DONE', fr: 'FAIRE', page: 2 },
  { n: 29, inf: 'DRAW', pret: 'DREW', pp: 'DRAWN', fr: 'DESSINER', page: 2 },
  { n: 30, inf: 'DREAM', pret: 'DREAMT', pp: 'DREAMT', fr: 'RÊVER', page: 2 },
  { n: 31, inf: 'DRINK', pret: 'DRANK', pp: 'DRUNK', fr: 'BOIRE', page: 2 },
  { n: 32, inf: 'DRIVE', pret: 'DROVE', pp: 'DRIVEN', fr: 'CONDUIRE', page: 2 },
  { n: 33, inf: 'EAT', pret: 'ATE', pp: 'EATEN', fr: 'MANGER', page: 2 },
  { n: 34, inf: 'FALL', pret: 'FELL', pp: 'FALLEN', fr: 'TOMBER', page: 2 },
  { n: 35, inf: 'FEED', pret: 'FED', pp: 'FED', fr: 'NOURRIR', page: 2 },
  { n: 36, inf: 'FEEL', pret: 'FELT', pp: 'FELT', fr: '(SE) SENTIR, RESSENTIR', page: 2 },
  { n: 37, inf: 'FIGHT', pret: 'FOUGHT', pp: 'FOUGHT', fr: 'COMBATTRE, SE BATTRE', page: 2 },
  { n: 38, inf: 'FIND', pret: 'FOUND', pp: 'FOUND', fr: 'TROUVER', page: 2 },
  { n: 39, inf: 'FLY', pret: 'FLEW', pp: 'FLOWN', fr: "VOLER (EN L'AIR)", page: 2 },
  { n: 40, inf: 'FORECAST', pret: 'FORECAST', pp: 'FORECAST', fr: 'PRÉVOIR', page: 2 },
  { n: 41, inf: 'FORBID', pret: 'FORBADE', pp: 'FORBIDDEN', fr: 'INTERDIRE', page: 2 },
  { n: 42, inf: 'FORGET', pret: 'FORGOT', pp: 'FORGOTTEN', fr: 'OUBLIER', page: 2 },
  { n: 43, inf: 'FORGIVE', pret: 'FORGAVE', pp: 'FORGIVEN', fr: 'PARDONNER', page: 2 },
  { n: 44, inf: 'FREEZE', pret: 'FROZE', pp: 'FROZEN', fr: 'GELER', page: 2 },
  { n: 45, inf: 'GET', pret: 'GOT', pp: 'GOT', fr: 'RECEVOIR, OBTENIR', page: 2 },
  { n: 46, inf: 'GIVE', pret: 'GAVE', pp: 'GIVEN', fr: 'DONNER', page: 2 },
  { n: 47, inf: 'GO', pret: 'WENT', pp: 'GONE', fr: 'ALLER', page: 2 },
  { n: 48, inf: 'GROW', pret: 'GREW', pp: 'GROWN', fr: 'POUSSER, GRANDIR', page: 2 },
  { n: 49, inf: 'HAVE', pret: 'HAD', pp: 'HAD', fr: 'AVOIR', page: 2 },

  // Страница 3: HANG (50) … QUIT (74).
  { n: 50, inf: 'HANG', pret: 'HUNG', pp: 'HUNG', fr: 'ACCROCHER, PENDRE', page: 3 },
  { n: 51, inf: 'HEAR', pret: 'HEARD', pp: 'HEARD', fr: 'ENTENDRE', page: 3 },
  { n: 52, inf: 'HIDE', pret: 'HID', pp: 'HIDDEN', fr: '(SE) CACHER', page: 3 },
  { n: 53, inf: 'HIT', pret: 'HIT', pp: 'HIT', fr: 'FRAPPER', page: 3 },
  { n: 54, inf: 'HOLD', pret: 'HELD', pp: 'HELD', fr: 'TENIR', page: 3 },
  { n: 55, inf: 'HURT', pret: 'HURT', pp: 'HURT', fr: 'BLESSER, FAIRE MAL', page: 3 },
  { n: 56, inf: 'KEEP', pret: 'KEPT', pp: 'KEPT', fr: 'GARDER', page: 3 },
  { n: 57, inf: 'KNOW', pret: 'KNEW', pp: 'KNOWN', fr: 'SAVOIR, CONNAÎTRE', page: 3 },
  { n: 58, inf: 'LAY', pret: 'LAID', pp: 'LAIN', fr: 'POSER, ÉTENDRE', page: 3 },
  { n: 59, inf: 'LEAD', pret: 'LED', pp: 'LED', fr: 'MENER, GUIDER', page: 3 },
  { n: 60, inf: 'LEARN', pret: 'LEARNT/-ED', pp: 'LEARNT/-ED', fr: 'APPRENDRE', page: 3 },
  { n: 61, inf: 'LEAVE', pret: 'LEFT', pp: 'LEFT', fr: 'PARTIR, QUITTER', page: 3 },
  { n: 62, inf: 'LEND', pret: 'LENT', pp: 'LENT', fr: 'PRÊTER', page: 3 },
  { n: 63, inf: 'LET', pret: 'LET', pp: 'LET', fr: 'LAISSER', page: 3 },
  { n: 64, inf: 'LIE', pret: 'LAY', pp: 'LAIN', fr: "(S') ALLONGER", page: 3 },
  { n: 65, inf: 'LIGHT', pret: 'LIT', pp: 'LIT', fr: 'ALLUMER', page: 3 },
  { n: 66, inf: 'LOSE', pret: 'LOST', pp: 'LOST', fr: 'PERDRE', page: 3 },
  { n: 67, inf: 'MAKE', pret: 'MADE', pp: 'MADE', fr: 'FAIRE, FABRIQUER', page: 3 },
  { n: 68, inf: 'MEAN', pret: 'MEANT', pp: 'MEANT', fr: 'VOULOIR DIRE, SIGNIFIER', page: 3 },
  { n: 69, inf: 'MEET', pret: 'MET', pp: 'MET', fr: 'RENCONTRER', page: 3 },
  { n: 70, inf: 'OVERCOME', pret: 'OVERCAME', pp: 'OVERCOME', fr: 'SURMONTER, VAINCRE', page: 3 },
  { n: 71, inf: 'OVERTHROW', pret: 'OVERTHREW', pp: 'OVERTHROWN', fr: 'RENVERSER', page: 3 },
  { n: 72, inf: 'PAY', pret: 'PAID', pp: 'PAID', fr: 'PAYER', page: 3 },
  { n: 73, inf: 'PUT', pret: 'PUT', pp: 'PUT', fr: 'METTRE', page: 3 },
  { n: 74, inf: 'QUIT', pret: 'QUIT', pp: 'QUIT', fr: 'ABANDONNER, ARRÊTER', page: 3 },

  // Страница 4: READ (75) … SPELL (99).
  { n: 75, inf: 'READ', pret: 'READ', pp: 'READ', fr: 'LIRE', page: 4 },
  { n: 76, inf: 'RIDE', pret: 'RODE', pp: 'RIDDEN', fr: 'MONTER, ALLER À (VÉLO/CHEVAL)', page: 4 },
  { n: 77, inf: 'RING', pret: 'RANG', pp: 'RUNG', fr: 'SONNER', page: 4 },
  { n: 78, inf: 'RISE', pret: 'ROSE', pp: 'RISEN', fr: '(SE) LEVER', page: 4 },
  { n: 79, inf: 'RUN', pret: 'RAN', pp: 'RUN', fr: 'COURIR', page: 4 },
  { n: 80, inf: 'SAY', pret: 'SAID', pp: 'SAID', fr: 'DIRE', page: 4 },
  { n: 81, inf: 'SEE', pret: 'SAW', pp: 'SEEN', fr: 'VOIR', page: 4 },
  { n: 82, inf: 'SELL', pret: 'SOLD', pp: 'SOLD', fr: 'VENDRE', page: 4 },
  { n: 83, inf: 'SEND', pret: 'SENT', pp: 'SENT', fr: 'ENVOYER', page: 4 },
  { n: 84, inf: 'SET', pret: 'SET', pp: 'SET', fr: 'INSTALLER, POSER', page: 4 },
  { n: 85, inf: 'SEEK', pret: 'SOUGHT', pp: 'SOUGHT', fr: 'CHERCHER', page: 4 },
  { n: 86, inf: 'SEW', pret: 'SEWED', pp: 'SEWN', fr: 'COUDRE', page: 4 },
  { n: 87, inf: 'SHAKE', pret: 'SHOOK', pp: 'SHAKEN', fr: 'SECOUER', page: 4 },
  { n: 88, inf: 'SHINE', pret: 'SHONE', pp: 'SHONE', fr: 'BRILLER', page: 4 },
  { n: 89, inf: 'SHOOT', pret: 'SHOT', pp: 'SHOT', fr: 'TIRER (ARME, BALLON)', page: 4 },
  { n: 90, inf: 'SHOW', pret: 'SHOWED', pp: 'SHOWN', fr: 'MONTRER', page: 4 },
  { n: 91, inf: 'SHUT', pret: 'SHUT', pp: 'SHUT', fr: 'FERMER', page: 4 },
  { n: 92, inf: 'SING', pret: 'SANG', pp: 'SUNG', fr: 'CHANTER', page: 4 },
  { n: 93, inf: 'SINK', pret: 'SANK', pp: 'SUNK', fr: 'COULER', page: 4 },
  { n: 94, inf: 'SIT', pret: 'SAT', pp: 'SAT', fr: "S'ASSEOIR", page: 4 },
  { n: 95, inf: 'SLEEP', pret: 'SLEPT', pp: 'SLEPT', fr: 'DORMIR', page: 4 },
  { n: 96, inf: 'SLIDE', pret: 'SLID', pp: 'SLID', fr: 'GLISSER', page: 4 },
  { n: 97, inf: 'SMELL', pret: 'SMELT', pp: 'SMELT', fr: 'SENTIR', page: 4 },
  { n: 98, inf: 'SPEAK', pret: 'SPOKE', pp: 'SPOKEN', fr: 'PARLER', page: 4 },
  { n: 99, inf: 'SPELL', pret: 'SPELT/-ED', pp: 'SPELT/-ED', fr: 'ÉPELER', page: 4 },

  // Страница 5: SPEND (100) … WRITE (125).
  { n: 100, inf: 'SPEND', pret: 'SPENT', pp: 'SPENT', fr: 'DÉPENSER (argent), PASSER (temps)', page: 5 },
  { n: 101, inf: 'SPILL', pret: 'SPILT/-ED', pp: 'SPILT/-ED', fr: 'RENVERSER', page: 5 },
  { n: 102, inf: 'SPLIT', pret: 'SPLIT', pp: 'SPLIT', fr: 'FENDRE, DIVISER', page: 5 },
  { n: 103, inf: 'SPOIL', pret: 'SPOILT', pp: 'SPOILT', fr: 'GÂCHER, GÂTER', page: 5 },
  { n: 104, inf: 'SPREAD', pret: 'SPREAD', pp: 'SPREAD', fr: 'RÉPANDRE', page: 5 },
  { n: 105, inf: 'STAND', pret: 'STOOD', pp: 'STOOD', fr: 'ÊTRE DEBOUT', page: 5 },
  { n: 106, inf: 'STEAL', pret: 'STOLE', pp: 'STOLEN', fr: 'VOLER, DÉROBER', page: 5 },
  { n: 107, inf: 'STICK', pret: 'STUCK', pp: 'STUCK', fr: 'COLLER', page: 5 },
  { n: 108, inf: 'STING', pret: 'STUNG', pp: 'STUNG', fr: 'PIQUER', page: 5 },
  { n: 109, inf: 'STRIKE', pret: 'STRUCK', pp: 'STRUCK', fr: 'FRAPPER', page: 5 },
  { n: 110, inf: 'SWEAR', pret: 'SWORE', pp: 'SWORN', fr: 'JURER', page: 5 },
  { n: 111, inf: 'SWIM', pret: 'SWAM', pp: 'SWUM', fr: 'NAGER', page: 5 },
  { n: 112, inf: 'SWING', pret: 'SWUNG', pp: 'SWUNG', fr: '(SE) BALANCER', page: 5 },
  { n: 113, inf: 'TAKE', pret: 'TOOK', pp: 'TAKEN', fr: 'PRENDRE', page: 5 },
  { n: 114, inf: 'TEACH', pret: 'TAUGHT', pp: 'TAUGHT', fr: 'ENSEIGNER', page: 5 },
  { n: 115, inf: 'TEAR', pret: 'TORE', pp: 'TORN', fr: 'DÉCHIRER', page: 5 },
  { n: 116, inf: 'TELL', pret: 'TOLD', pp: 'TOLD', fr: 'DIRE, RACONTER', page: 5 },
  { n: 117, inf: 'THINK', pret: 'THOUGHT', pp: 'THOUGHT', fr: 'PENSER', page: 5 },
  { n: 118, inf: 'THROW', pret: 'THREW', pp: 'THROWN', fr: 'JETER', page: 5 },
  { n: 119, inf: 'UNDERSTAND', pret: 'UNDERSTOOD', pp: 'UNDERSTOOD', fr: 'COMPRENDRE', page: 5 },
  { n: 120, inf: 'WAKE', pret: 'WOKE', pp: 'WOKEN', fr: '(SE) RÉVEILLER', page: 5 },
  { n: 121, inf: 'WEAR', pret: 'WORE', pp: 'WORN', fr: 'PORTER (VÊTEMENT)', page: 5 },
  { n: 122, inf: 'WEEP', pret: 'WEPT', pp: 'WEPT', fr: 'PLEURER', page: 5 },
  { n: 123, inf: 'WIN', pret: 'WON', pp: 'WON', fr: 'GAGNER', page: 5 },
  { n: 124, inf: 'WITHDRAW', pret: 'WITHDREW', pp: 'WITHDRAWN', fr: "(SE) RETIRER", page: 5 },
  { n: 125, inf: 'WRITE', pret: 'WROTE', pp: 'WRITTEN', fr: 'ÉCRIRE', page: 5 },
];
