// Корпус фраз тренажёра чтения вслух: авторские фразы, подобранные так,
// чтобы суммарно задействовать все правила чтения из frenchReadingRules.
// ruleIds — главные правила фразы (для карточки «что тренируем»).

export interface LecturePhrase {
  text: string;
  ipa: string;
  translation: string;
  /** Главные правила чтения, на которые нацелена фраза. */
  ruleIds: string[];
}

export const LECTURE_PHRASES: LecturePhrase[] = [
  { text: 'Le bateau jaune est sur l\'eau chaude.',
    ipa: 'lə bato ʒon ɛ syʁ lo ʃod',
    translation: 'Жёлтая лодка на тёплой воде.',
    ruleIds: ['eau', 'j-ge', 'ch', 'final-e'] },
  { text: 'Toujours rouge, la roue tourne sous le pont.',
    ipa: 'tuʒuʁ ʁuʒ la ʁu tuʁn su lə pɔ̃',
    translation: 'Всегда красное, колесо крутится под мостом.',
    ruleIds: ['ou', 'r', 'nasal-on'] },
  { text: 'Tu as vu la rue et la lune ?',
    ipa: 'ty a vy la ʁy e la lyn',
    translation: 'Ты видел улицу и луну?',
    ruleIds: ['u', 'r', 'final-e'] },
  { text: 'Moi, je bois trois fois par mois.',
    ipa: 'mwa ʒə bwa tʁwa fwa paʁ mwa',
    translation: 'Я пью три раза в месяц.',
    ruleIds: ['oi', 'e-caduc', 'final-cons'] },
  { text: 'Cette nuit, il fait huit degrés, je suis à la cuisine.',
    ipa: 'sɛt nɥi il fɛ ɥit dəɡʁe ʒə sɥi a la kɥizin',
    translation: 'Этой ночью восемь градусов, я на кухне.',
    ruleIds: ['ui', 'e-caduc', 'final-e'] },
  { text: 'Ma sœur heureuse a deux fleurs bleues.',
    ipa: 'ma sœʁ øʁøz a dø flœʁ blø',
    translation: 'У моей счастливой сестры два синих цветка.',
    ruleIds: ['eu', 's-z', 'final-cons'] },
  { text: 'L\'été, le café du musée est fermé.',
    ipa: 'lete lə kafe dy myze ɛ fɛʁme',
    translation: 'Летом кафе музея закрыто.',
    ruleIds: ['e-acute', 'c-hard', 's-z', 'u'] },
  { text: 'Mon père achète du lait frais à la fête.',
    ipa: 'mɔ̃ pɛʁ aʃɛt dy lɛ fʁɛ a la fɛt',
    translation: 'Мой отец покупает свежее молоко на празднике.',
    ruleIds: ['e-grave', 'ch', 'nasal-on', 'final-cons'] },
  { text: 'Vous allez parler et manger chez Léa.',
    ipa: 'vuz‿ale paʁle e mɑ̃ʒe ʃe lea',
    translation: 'Вы будете говорить и есть у Леа.',
    ruleIds: ['er-ez', 'j-ge', 'ch', 'nasal-an'] },
  { text: 'Le petit ne me le redemande pas.',
    ipa: 'lə pəti nə mə lə ʁədəmɑ̃d pa',
    translation: 'Малыш меня об этом снова не просит.',
    ruleIds: ['e-caduc', 'nasal-an', 'final-cons'] },
  { text: 'Ils parlent et regardent la table ronde.',
    ipa: 'il paʁl e ʁəɡaʁd la tabl ʁɔ̃d',
    translation: 'Они говорят и смотрят на круглый стол.',
    ruleIds: ['ent-verb', 'final-e', 'nasal-on'] },
  { text: 'Le grand enfant entre en chantant.',
    ipa: 'lə ɡʁɑ̃t‿ɑ̃fɑ̃ ɑ̃tʁ ɑ̃ ʃɑ̃tɑ̃',
    translation: 'Большой ребёнок входит с песней.',
    ruleIds: ['nasal-an', 'ch', 'final-cons'] },
  { text: 'Ce bon garçon mange onze bonbons.',
    ipa: 'sə bɔ̃ ɡaʁsɔ̃ mɑ̃ʒ ɔ̃z bɔ̃bɔ̃',
    translation: 'Этот хороший мальчик ест одиннадцать конфет.',
    ruleIds: ['nasal-on', 'c-soft', 'j-ge'] },
  { text: 'Le matin, un lapin brun mange du pain.',
    ipa: 'lə matɛ̃ œ̃ lapɛ̃ bʁœ̃ mɑ̃ʒ dy pɛ̃',
    translation: 'Утром коричневый кролик ест хлеб.',
    ruleIds: ['nasal-in', 'nasal-an', 'u'] },
  { text: 'La bonne année d\'Anne est pleine de personnes.',
    ipa: 'la bɔn ane dan ɛ plɛn də pɛʁsɔn',
    translation: 'Хороший год Анны полон людей.',
    ruleIds: ['denasal', 'e-caduc', 'final-e'] },
  { text: 'Le chat cherche la chance chez le chef.',
    ipa: 'lə ʃa ʃɛʁʃ la ʃɑ̃s ʃe lə ʃɛf',
    translation: 'Кот ищет удачу у шефа.',
    ruleIds: ['ch', 'nasal-an', 'final-cons'] },
  { text: 'La girafe rouge joue dans le jardin de Jules.',
    ipa: 'la ʒiʁaf ʁuʒ ʒu dɑ̃ lə ʒaʁdɛ̃ də ʒyl',
    translation: 'Красный жираф играет в саду Жюля.',
    ruleIds: ['j-ge', 'ou', 'nasal-in'] },
  { text: 'En Espagne, la montagne gagne en charme.',
    ipa: 'ɑ̃n‿ɛspaɲ la mɔ̃taɲ ɡaɲ ɑ̃ ʃaʁm',
    translation: 'В Испании гора становится ещё очаровательнее.',
    ruleIds: ['gn', 'nasal-an', 'ch'] },
  { text: 'Ce garçon français commence son leçon de cinéma.',
    ipa: 'sə ɡaʁsɔ̃ fʁɑ̃sɛ kɔmɑ̃s sɔ̃ ləsɔ̃ də sinema',
    translation: 'Этот французский мальчик начинает свой урок кино.',
    ruleIds: ['c-soft', 'c-hard', 'nasal-on'] },
  { text: 'Qui écoute la musique classique au quai ?',
    ipa: 'ki ekut la myzik klasik o ke',
    translation: 'Кто слушает классическую музыку на набережной?',
    ruleIds: ['qu', 'ou', 'ss', 'eau'] },
  { text: 'Le poisson est un cadeau, le poison est un danger.',
    ipa: 'lə pwasɔ̃ ɛt‿œ̃ kado lə pwazɔ̃ ɛt‿œ̃ dɑ̃ʒe',
    translation: 'Рыба — подарок, яд — опасность.',
    ruleIds: ['ss', 's-z', 'oi', 'eau'] },
  { text: 'L\'homme heureux habite en haut, à l\'hôtel.',
    ipa: 'lɔm øʁø abit ɑ̃ o a lotɛl',
    translation: 'Счастливый человек живёт наверху, в отеле.',
    ruleIds: ['h-mute', 'eu', 'nasal-an'] },
  { text: 'La photo de la pharmacie est dans mon téléphone.',
    ipa: 'la fɔto də la faʁmasi ɛ dɑ̃ mɔ̃ telefɔn',
    translation: 'Фото аптеки — в моём телефоне.',
    ruleIds: ['ph', 'e-acute', 'nasal-on'] },
  { text: 'La famille de la fille brille au soleil en juillet.',
    ipa: 'la famij də la fij bʁij o sɔlɛj ɑ̃ ʒɥijɛ',
    translation: 'Семья девочки сияет на солнце в июле.',
    ruleIds: ['ill', 'ui', 'eau'] },
  { text: 'Attention : l\'addition de la nation est une question.',
    ipa: 'atɑ̃sjɔ̃ ladisjɔ̃ də la nasjɔ̃ ɛt‿yn kɛstjɔ̃',
    translation: 'Внимание: счёт нации — это вопрос.',
    ruleIds: ['tion', 'nasal-an', 'qu'] },
  { text: 'Bien sûr, le chien vient au moins loin.',
    ipa: 'bjɛ̃ syʁ lə ʃjɛ̃ vjɛ̃ o mwɛ̃ lwɛ̃',
    translation: 'Конечно, собака приходит хотя бы издалека.',
    ruleIds: ['ien', 'oin', 'u', 'ch'] },
  { text: 'À l\'examen, le taxi coûte exactement deux euros.',
    ipa: 'a lɛɡzamɛ̃ lə taksi kut ɛɡzaktəmɑ̃ dø‿z‿øʁo',
    translation: 'На экзамене такси стоит ровно два евро.',
    ruleIds: ['x', 'ou', 'eu'] },
  { text: 'Le style d\'Yves est typique des pays du sud.',
    ipa: 'lə stil div ɛ tipik de pei dy syd',
    translation: 'Стиль Ива типичен для южных стран.',
    ruleIds: ['y', 'u', 'final-cons'] },
  { text: 'Vous êtes mes amis, ils ont un grand appartement.',
    ipa: 'vuz‿ɛt mez‿ami ilz‿ɔ̃t‿œ̃ ɡʁɑ̃t‿apaʁtəmɑ̃',
    translation: 'Вы мои друзья, у них большая квартира.',
    ruleIds: ['final-cons', 'nasal-an', 'nasal-on'] },
  { text: 'Elle est née à Nice et elle danse sans se presser.',
    ipa: 'ɛl ɛ ne a nis e ɛl dɑ̃s sɑ̃ sə pʁese',
    translation: 'Она родилась в Ницце и танцует не спеша.',
    ruleIds: ['c-soft', 'nasal-an', 'ss', 'e-acute'] },
];
